### ISSUE TITLE
py-aspio problem: 'dlvhex2 no such file or directory'

### ISSUE THREAD

**Issue by ImpossibleSquish** [hexhex/py-aspio#1]
Hello

I'm not sure if this is a py-aspio bug or if I just have my dlvhex executable stored in the wrong folder, but when I try to run code that uses py-aspio, I get the following error:

Traceback (most recent call last):
  File "pythontest.py", line 15, in <module>
    for result in prog.solve(nodes, arcs):
  File "/usr/local/lib/python3.5/site-packages/aspio/program.py", line 166, in solve
    options=options
  File "/usr/local/lib/python3.5/site-packages/aspio/solver/dlvhex2.py", line 82, in run
    stderr=subprocess.PIPE,
  File "/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'dlvhex2'

I downloaded dlvhex2 recently so I assume I have the most recent version. I have it stored in a folder on my desktop. Do I need to move it to a folder where python can find it, or do I need to add its current location to my pythonpath, or is the problem something else?

**Comment by peschue** [comment]
Please either do "make install" for dlvhex2 so that it automatically is installed into the system and you can call it from anywhere in the shell with "dlvhex".

Or put the path to the dlvhex2 binary into the PATH environment variable and the path to the dlvhex2 libraries into LD_LIBRARY_PATH.

**Comment by JakobR** [comment]
By default, py-aspio looks for the `dlvhex2` executable in the locations specified by the PATH environment variable, so the easiest solution would be one of the two methods mentioned by @peschue.

**Comment by ImpossibleSquish** [comment]
Hello

Thank you, and sorry for the late reply; I've been trying to install dlvhex from source for the last few days but it hasn't been working. I'll try the second method mentioned, for which I assume I just need the binary and won't need to install from source.

Thank you for your help
