### ISSUE TITLE
Safe rules not working with pyaspio

### ISSUE THREAD

**Issue by ImpossibleSquish** [hexhex/py-aspio#2]
Hello

When using py-aspio I've noticed a strange issue. If I run the following code (from within a python file):

    %!  INPUT (Set<Thing> things) {
    %!      exists(n.name) for n in things;
    %!  }

    %!  OUTPUT {
    %!	testing = set { query: testing(X); content: X; };
    %!  }

    testing(X):-exists(X), thing(X).
    thing(book).
    thing(knife).

I get an empty output (the set 'testing' is empty).
If I add exists(book) to the code manually (writing it in as a rule instead of including it in the input specification), then book is included in the output set.
If I remove 'thing(X)' from the body of the testing(X) rule, then the output includes both book and knife, which is the behaviour I want (book and knife are both included in the input set 'things').
However with my real code (this is just a simple example) I can't remove the equivalent of 'thing(X)' from rules because I want to use SPARC to translate a sparc-formatted file into a basic asp-file, and in the translation process SPARC automatically tries to make rules 'safe' by including the requirement that they be of the right sort.

Why is this happening, and is there any way I can fix it?

**Comment by JakobR** [comment]
Hello,

the issue is a bit subtle: dlvhex distinguishes between a normal constant symbol `book` and a quoted string constant `"book"`. So it should work if you change the last two lines to:

```
thing("book").
thing("knife").
```

py-aspio always maps Python strings to quoted string constants (for consistency; so it works with all kinds of strings we get from the Python code).

I hope this helped!

**Comment by ImpossibleSquish** [comment]
Thank you for your help :)

**Comment by JakobR** [comment]
No problem :)
